import Head from 'next/head';
import TransactionDetailContent from '@/components/organisms/TransactionDetailContent';
import { jwtDecode } from 'jwt-decode';
import {
  HistoryTransactionTypes,
  JTWPayloadTypes,
  UserTypes,
} from '@/services/data-types';
import { getTransactionDetail } from '@/services/member';

interface TransactionsDetailProps {
  transactionDetail: HistoryTransactionTypes;
}

export default function TransactionsDetail(props: TransactionsDetailProps) {
  const { transactionDetail } = props;

  return (
    <>
      <Head>
        <title>StoreGG | Transactions Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="transactions-detail overflow-auto">
        <TransactionDetailContent data={transactionDetail} />
      </section>
    </>
  );
}

interface GetServerSideProps {
  req: {
    cookies: {
      token: string;
    };
  };
  params: {
    id: string;
  };
}

export async function getServerSideProps({ req, params }: GetServerSideProps) {
  const { id } = params;
  const { token } = req.cookies;

  if (!token) {
    return {
      redirect: {
        destination: '/sign-in',
        permanent: false,
      },
    };
  }

  const jwtToken = Buffer.from(token, 'base64').toString('ascii');
  const payload: JTWPayloadTypes = jwtDecode(jwtToken);
  const userPayload: UserTypes = payload.player;
  const IMG = process.env.NEXT_PUBLIC_IMAGE;
  userPayload.avatar = `${IMG}/${userPayload.avatar}`;

  const response = await getTransactionDetail(id, jwtToken);

  return {
    props: {
      transactionDetail: response.data,
    },
  };
}
