import Head from 'next/head';
import Sidebar from '@/components/organisms/Sidebar';
import TransactionContent from '@/components/organisms/TransactionContent';

export default function Transactions() {
  return (
    <>
      <Head>
        <title>StoreGG | Transactions Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="transactions overflow-auto">
        <Sidebar activeMenu="transaction" />
        <TransactionContent />
      </section>
    </>
  );
}
