import Head from 'next/head';
import Sidebar from '@/components/organisms/Sidebar';
import OverviewContent from '@/components/organisms/OverviewContent';

export default function Member() {
  return (
    <>
      <Head>
        <title>StoreGG | Member Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="overview overflow-auto">
        <Sidebar />
        <OverviewContent />
      </section>
    </>
  );
}
