import Head from 'next/head';
import Sidebar from '@/components/organisms/Sidebar';
import OverviewContent from '@/components/organisms/OverviewContent';
import { jwtDecode } from 'jwt-decode';
import { JTWPayloadTypes, UserTypes } from '@/services/data-types';

export default function Member() {
  return (
    <>
      <Head>
        <title>StoreGG | Member Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="overview overflow-auto">
        <Sidebar activeMenu="overview" />
        <OverviewContent />
      </section>
    </>
  );
}

interface GetServerSideProps {
  req: {
    cookies: {
      token: string;
    };
  };
}

export async function getServerSideProps({ req }: GetServerSideProps) {
  const { token } = req.cookies;

  if (!token) {
    return {
      redirect: {
        destination: '/sign-in',
        permanent: false,
      },
    };
  }

  const jwtToken = Buffer.from(token, 'base64').toString('ascii');
  const payload: JTWPayloadTypes = jwtDecode(jwtToken);
  const userPayload: UserTypes = payload.player;
  const IMG = process.env.NEXT_PUBLIC_IMAGE;
  userPayload.avatar = `${IMG}/${userPayload.avatar}`;

  return {
    props: {},
  };
}
