import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import SignUpForm from '@/components/organisms/SignUpForm';

export default function SignUp() {
  return (
    <>
      <Head>
        <title>StoreGG | Sign-Up Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="sign-up mx-auto pt-lg-100 pb-lg-100 pt-30 pb-47">
        <div className="container mx-auto">
          <form action="">
            <div className="pb-50">
              <Link href="/" legacyBehavior>
                <a className="navbar-brand">
                  <Image
                    src="/icon/logo.svg"
                    width={60}
                    height={60}
                    alt="logo"
                  />
                </a>
              </Link>
            </div>
            <SignUpForm />
          </form>
        </div>
      </section>
    </>
  );
}
